Add build information to fp
- Use vergen to capture build information
- Add version command to fp
- Add manifest files to s3 buckets
- Add (background) version check

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -7,8 +7,27 @@ on:
 name: Publish binaries
 
 jobs:
+  validate-release:
+    name: Validate release ${{ github.event.release.tag_name }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 1
+
+      - name: validate version
+        if: github.event_name == 'workflow_dispatch'
+        run: |
+          FP_VERSION=$(cat "Cargo.toml" | grep '^version' | awk '{ split($0,version,"=") ; gsub(/[\ \"]/, "", version[2]) ; print version[2] }')
+          if [ "v${FP_VERSION}" != "${{ github.event.release.tag_name }}" ]; then
+            echo "::error file=Cargo.toml::Version set in Cargo.toml (v${FP_VERSION}) does not match release version (${{ github.event.release.tag_name }})"
+            exit 1
+          fi
+
   build-upload-assets:
     name: build-upload-assets
+    needs: validate-release
     runs-on: ${{ matrix.os }}
     env:
       CARGO: cargo
@@ -74,6 +93,11 @@ jobs:
         if: matrix.build == 'linux_x86_64' || matrix.build == 'macos_x86_64'
         run: strip "target/${{ matrix.target }}/release/fp"
 
+      - name: Release version information
+        run: |
+          target/${{ matrix.target }}/release/fp version
+          target/${{ matrix.target }}/release/fp version -o json > version.json
+
       # - name: Strip release binary (arm)
       #   if: matrix.build == 'macos_aarch64'
       #   run: |
@@ -87,7 +111,7 @@ jobs:
         if: github.event_name == 'workflow_dispatch'
         uses: actions/upload-artifact@v2
         with:
-          name: fp-${{ matrix.build }}
+          name: fp-${{ matrix.target }}
           path: target/${{ matrix.target }}/release/fp
           if-no-files-found: error
           retention-days: 1
@@ -100,7 +124,7 @@ jobs:
         with:
           upload_url: ${{ github.event.release.upload_url }}
           asset_path: target/${{ matrix.target }}/release/fp
-          asset_name: fp-${{ matrix.build }}
+          asset_name: fp-${{ matrix.target }}
           asset_content_type: application/octet-stream
 
       - name: Configure AWS Credentials
@@ -117,7 +141,7 @@ jobs:
           aws s3 cp \
             --acl public-read \
             target/${{ matrix.target }}/release/fp \
-            s3://fp.dev/fp/${{ github.event.release.tag_name }}/${{ matrix.build }}/fp
+            s3://fp.dev/fp/${{ github.event.release.tag_name }}/${{ matrix.target }}/fp
 
   update-latest-s3:
     name: update-latest-s3
